[phases.setup]
nixPkgs = [python311]
[phases.install]
cmds = ["pip install -r backend/requirements.txt"]
[phases.start]
cmd = "cd backend && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
