# Generated by Django 6.0.3 on 2026-03-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0002_categoriamenu_servicioadicional_categoria_platillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='precio_hora_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicios_incluidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='duracion_horas',
            field=models.IntegerField(default=5),
        ),
    ]
