# Generated by Django 6.0.3 on 2026-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0003_paquete_notas_paquete_precio_hora_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/'),
        ),
    ]
