# Generated by Django 6.0.3 on 2026-03-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0004_alter_paquete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='paquetes/galeria/')),
                ('orden', models.IntegerField(default=0)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='sirlux.paquete')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
