# Generated by Django 6.0.3 on 2026-03-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0005_imagenpaquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platillos/'),
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/portadas/'),
        ),
    ]
