# Generated by Django 6.0.3 on 2026-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0006_platillo_imagen_servicioadicional_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galerías',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menus/platillos/'),
        ),
        migrations.AlterField(
            model_name='servicioadicional',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='adicionales/'),
        ),
    ]
