# Generated by Django 6.0.3 on 2026-03-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0007_galeria_alter_platillo_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('representante_salon', models.CharField(default='Graciela Herrera Ramírez', max_length=200)),
                ('lugar_evento', models.CharField(default='2 de Abril 2503 Col. El Carmen, Apizaco, Tlax.', max_length=255)),
                ('cantidad_personas', models.PositiveIntegerField(default=0)),
                ('duracion_horas', models.PositiveIntegerField(default=5)),
                ('total_operacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('anticipo_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('esta_firmado', models.BooleanField(default=False)),
                ('notas_especiales', models.TextField(blank=True, null=True)),
                ('reservacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='sirlux.reservacion')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
