# Generated by Django 6.0.3 on 2026-03-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0009_pagocontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Paterno'),
        ),
    ]
