# Generated by Django 6.0.3 on 2026-03-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0010_alter_usuario_apellido_paterno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
