# Generated by Django 6.0.3 on 2026-03-13 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0011_remove_usuario_correo_remove_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(default=5, verbose_name='Calificación')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False, verbose_name='¿Aprobado para mostrar?')),
                ('reservacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonio', to='sirlux.reservacion')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
