# Generated by Django 5.2.8 on 2026-03-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0013_reservacion_platillos_seleccionados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='domicilio_consumidor',
            field=models.TextField(blank=True, null=True, verbose_name='Domicilio del Consumidor'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='telefono_consumidor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Evento'),
        ),
    ]
