# Generated by Django 5.2.8 on 2026-03-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0014_contrato_domicilio_consumidor_contrato_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='domicilio_contacto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='nombre_festejado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
