# Generated by Django 5.2.8 on 2026-03-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0015_reservacion_domicilio_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='horas_adicionales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
