# Generated by Django 5.2.8 on 2026-03-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0013_alter_categoriamenu_id_alter_cliente_id_and_more'),
        ('sirlux', '0016_reservacion_horas_adicionales'),
    ]

    operations = [
    ]
