# Generated by Django 5.2.8 on 2026-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0018_alter_categoriamenu_id_alter_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioadicional',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicioadicional',
            name='tipo_cobro',
            field=models.CharField(choices=[('Por Evento', 'Por Evento'), ('Por Persona', 'Por Persona')], default='Por Evento', max_length=20),
        ),
    ]
