# Generated by Django 5.2.8 on 2026-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0021_reset_all_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_evento',
            field=models.DateField(db_index=True),
        ),
    ]
