# Generated by Django 5.2.8 on 2026-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0022_alter_reservacion_fecha_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamenu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menus/categorias/'),
        ),
    ]
